from .MainScene import MainMenuScene
from .DocumentsDataScene import DocumentsDataScene
from .PersonalDataScene import PersonalDataScene
from .TargetPlaceScene import TargetPlaceScene
from .PanelSelectionScene import PanelSelectionScene
from .InvertorSelectionScene import InvertorSelectionScene
from .SmartMeterSelectionScene import SmartMeterSelectionScene
from .SummaryScene import SummaryScene